import type { IdeaFormData, ValidationReport, ProjectKnowledge, ObsidianNote, MarketIntelligence } from './types';
import { SECTION_KEYS, SECTION_LABELS } from './knowledge';

/** Makni znakove nedopuštene u nazivima fajlova (Windows + Obsidian) i wikilink konflikte. */
export function safeName(s: string): string {
  return (s || 'Projekt')
    .replace(/[\\/:*?"<>|#^[\]]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 80) || 'Projekt';
}

const ROOT = 'AI Validator';

type Lang = 'hr' | 'en';

const L = {
  hr: {
    score: 'Viability score',
    buy: 'Kupio bi',
    maybe: 'Možda',
    reject: 'Odbija',
    summary: 'Sažetak',
    audience: 'Ciljna publika',
    rejection: 'Zid odbijanja',
    questions: 'Pitanja iz mase',
    plan: 'Akcijski plan',
    segments: 'Segmenti',
    pricing: 'Cijena',
    interview: 'Intervjui',
    conversion: 'Plan preokreta',
    plan_product: 'Proizvod',
    plan_marketing: 'Marketing',
    plan_pricing: 'Cijena',
    notes: 'Note',
    partOf: 'Dio projekta',
    profile: 'Profil',
    assumption: 'Pretpostavka vs stvarnost',
    reasonsToBuy: 'Glavni razlozi za kupnju',
    reasons: 'Razlozi odbijanja',
    quotes: 'Citati',
    plan_lever: 'Poluga',
    addresses: 'Uklanja',
    couldConvert: 'Procjena preokreta',
    effort: 'Trud',
    listenFor: 'Slušaj za',
    tests: 'Testira',
    whoToInterview: 'Koga intervjuirati',
    whereToFind: 'Gdje ih naći',
    avoid: 'Izbjegavaj',
    range: 'Prihvatljiv raspon',
    optimal: 'Optimalna cijena (OPP)',
    knowledge: 'Baza znanja',
    facts: 'Potvrđeno',
    gaps: 'Otvorena pitanja',
    generatedBy: 'Generirao AI Validator',
    market: 'Istraživanje tržišta',
    marketScope: 'Doseg',
    marketCompetitors: 'Konkurencija',
    marketGaps: 'Tržišne praznine',
    marketSignals: 'Signali',
    marketBattlecard: 'Prodajna kartica',
    marketWeaknesses: 'Slabosti',
    marketOurEdge: 'Naša prednost',
    marketResearched: 'Istraženo',
  },
  en: {
    score: 'Viability score',
    buy: 'Would buy',
    maybe: 'Maybe',
    reject: 'Rejects',
    summary: 'Summary',
    audience: 'Target audience',
    rejection: 'Wall of rejection',
    questions: 'Questions from the crowd',
    plan: 'Action plan',
    segments: 'Segments',
    pricing: 'Pricing',
    interview: 'Interviews',
    conversion: 'Conversion plan',
    plan_product: 'Product',
    plan_marketing: 'Marketing',
    plan_pricing: 'Pricing',
    notes: 'Notes',
    partOf: 'Part of project',
    profile: 'Profile',
    assumption: 'Assumption vs reality',
    reasonsToBuy: 'Top reasons to buy',
    reasons: 'Rejection reasons',
    quotes: 'Quotes',
    plan_lever: 'Lever',
    addresses: 'Addresses',
    couldConvert: 'Est. conversion',
    effort: 'Effort',
    listenFor: 'Listen for',
    tests: 'Tests',
    whoToInterview: 'Who to interview',
    whereToFind: 'Where to find them',
    avoid: 'Avoid',
    range: 'Acceptable range',
    optimal: 'Optimal price (OPP)',
    knowledge: 'Knowledge base',
    facts: 'Confirmed',
    gaps: 'Open questions',
    generatedBy: 'Generated by AI Validator',
    market: 'Market research',
    marketScope: 'Scope',
    marketCompetitors: 'Competition',
    marketGaps: 'Market gaps',
    marketSignals: 'Signals',
    marketBattlecard: 'Sales battlecard',
    marketWeaknesses: 'Weaknesses',
    marketOurEdge: 'Our edge',
    marketResearched: 'Researched',
  },
};

function fm(fields: Record<string, string | number | string[]>): string {
  const lines = ['---'];
  for (const [k, v] of Object.entries(fields)) {
    if (Array.isArray(v)) lines.push(`${k}: [${v.join(', ')}]`);
    else lines.push(`${k}: ${v}`);
  }
  lines.push('---');
  return lines.join('\n');
}

/**
 * Pretvori validacijski izvještaj (+ opcionalno bazu znanja) u set povezanih
 * Obsidian markdown nota. ČISTA funkcija — bez LLM-a, bez mreže, bez truncationa.
 * Hub nota linka na sve pod-note; svaka pod-nota linka natrag na hub.
 */
export function buildVaultNotes(
  idea: IdeaFormData,
  report: ValidationReport,
  knowledge: ProjectKnowledge | null,
  language: Lang,
  market?: MarketIntelligence | null
): ObsidianNote[] {
  const t = L[language];
  const project = safeName(report.meta.product_name || idea.product_name);
  const dir = `${ROOT}/${project}`;
  const notes: ObsidianNote[] = [];
  const childLinks: string[] = [];

  // Naziv pod-note je prefiksiran projektom da wikilinkovi budu jedinstveni u vaultu
  const sub = (label: string) => `${project} — ${label}`;
  const addNote = (label: string, body: string, tags: string[] = []) => {
    const title = sub(label);
    childLinks.push(`- [[${title}]]`);
    notes.push({
      path: `${dir}/${safeName(title)}.md`,
      markdown: `${fm({ tags: ['ai-validator', ...tags], project, source: 'AI Validator' })}

> ${t.partOf} [[${project}]]

# ${label}

${body.trim()}
`,
    });
  };

  const date = (report.meta.generated_at || new Date().toISOString()).slice(0, 10);

  // ── Pod-note ──
  addNote(t.summary, report.summary || '—', ['sazetak']);

  const ta = report.target_audience;
  addNote(
    t.audience,
    [
      `**${t.profile}:** ${ta.profile}`,
      '',
      `**${t.assumption}:** ${ta.assumption_vs_reality}`,
      '',
      `### ${t.reasonsToBuy}`,
      ...(ta.top_reasons_to_buy || []).map((r) => `- ${r}`),
    ].join('\n'),
    ['publika']
  );

  addNote(
    t.rejection,
    [
      `### ${t.reasons}`,
      ...report.rejection.reasons.map((r) => `- **${r.percentage}%** — ${r.reason}`),
      '',
      `### ${t.quotes}`,
      ...report.rejection.quotes.map((q) => `> ${q}`),
    ].join('\n'),
    ['odbijanje']
  );

  if (report.top_questions?.length) {
    addNote(
      t.questions,
      report.top_questions.map((q) => `- ${q}`).join('\n'),
      ['pitanja']
    );
  }

  const ap = report.action_plan;
  addNote(
    t.plan,
    [
      `### ${t.plan_product}`,
      ap.product,
      '',
      `### ${t.plan_marketing}`,
      ap.marketing,
      '',
      `### ${t.plan_pricing}`,
      ap.pricing,
    ].join('\n'),
    ['plan']
  );

  if (report.segments?.length) {
    addNote(
      t.segments,
      report.segments
        .map(
          (s) =>
            `### ${s.label} — ${s.score}/100\n${s.description}\n\n- ${t.buy}: ${s.intent.buy}% · ${t.maybe}: ${s.intent.maybe}% · ${t.reject}: ${s.intent.reject}%\n- ${s.verdict}`
        )
        .join('\n\n'),
      ['segmenti']
    );
  }

  if (report.pricing) {
    const p = report.pricing;
    addNote(
      t.pricing,
      [
        `**${t.optimal}:** ${p.currency}${p.opp}${p.unit}`,
        `**${t.range}:** ${p.currency}${p.range.low}–${p.currency}${p.range.high}${p.unit}`,
        '',
        p.verdict,
      ].join('\n'),
      ['cijena']
    );
  }

  if (report.interview) {
    const iv = report.interview;
    addNote(
      t.interview,
      [
        `**${t.whoToInterview}:** ${iv.who_to_interview}`,
        '',
        `**${t.whereToFind}:**`,
        ...iv.where_to_find.map((w) => `- ${w}`),
        '',
        ...iv.questions.map(
          (q, i) =>
            `${i + 1}. **${q.question}**\n   - ${t.tests}: ${q.why}\n   - ${t.listenFor}: ${q.listen_for}`
        ),
        '',
        `> ⚠️ ${t.avoid}: ${iv.avoid}`,
      ].join('\n'),
      ['intervju']
    );
  }

  if (report.conversion) {
    const c = report.conversion;
    addNote(
      t.conversion,
      [
        c.summary,
        '',
        ...c.levers.map(
          (lv) =>
            `### ${lv.change}\n- ${t.addresses}: ${lv.addresses}\n- ${t.couldConvert}: ~${lv.could_convert}%\n- ${t.effort}: ${lv.effort}`
        ),
      ].join('\n'),
      ['preokret']
    );
  }

  // ── Istraživanje tržišta (ako je proslijeđeno) ──
  if (market && (market.market_summary || market.competitors.length)) {
    const tierLabel: Record<string, string> = language === 'en'
      ? { direct: 'Direct', indirect: 'Indirect', substitute: 'Substitute' }
      : { direct: 'Izravni', indirect: 'Neizravni', substitute: 'Zamjena' };
    const horizonLabel: Record<string, string> = language === 'en'
      ? { tactical: 'Tactical', strategic: 'Strategic', directional: 'Directional' }
      : { tactical: 'Taktički', strategic: 'Strateški', directional: 'Usmjeravajući' };
    const researchedDate = (market.created_at || '').slice(0, 10);

    addNote(
      t.market,
      [
        `**${t.marketScope}:** ${market.scope.region} (${market.scope.scope})`,
        `**${t.marketResearched}:** ${researchedDate}`,
        '',
        market.market_summary,
        '',
        market.competitors.length ? `### ${t.marketCompetitors}` : '',
        ...market.competitors.map((c) => {
          const lines = [
            `#### ${c.name} — ${tierLabel[c.tier] || c.tier}${c.pricing ? ` · ${c.pricing}` : ''}`,
            c.summary,
            `- ${t.marketOurEdge}: ${c.our_edge}`,
          ];
          if (c.weaknesses.length) lines.push(`- ${t.marketWeaknesses}: ${c.weaknesses.join('; ')}`);
          if (c.battlecard) {
            lines.push(
              `- ${t.marketBattlecard}: "${c.battlecard.objection}" → "${c.battlecard.response}"${c.battlecard.proof ? ` (${c.battlecard.proof})` : ''}`
            );
          }
          return lines.join('\n');
        }),
        market.gaps.length ? `\n### ${t.marketGaps}\n` + market.gaps.map((g) => `- ${g}`).join('\n') : '',
        market.signals.length
          ? `\n### ${t.marketSignals}\n` + market.signals.map((s) => `- **${horizonLabel[s.horizon] || s.horizon}:** ${s.signal} → ${s.implication}`).join('\n')
          : '',
      ]
        .filter(Boolean)
        .join('\n'),
      ['trziste']
    );
  }

  // ── Baza znanja (ako je proslijeđena) ──
  if (knowledge) {
    for (const key of SECTION_KEYS) {
      const sec = knowledge.sections?.[key];
      if (!sec || (!sec.facts.length && !sec.gaps.length && !sec.summary)) continue;
      const label = `${t.knowledge}: ${SECTION_LABELS[key][language]}`;
      addNote(
        label,
        [
          sec.summary ? sec.summary + '\n' : '',
          sec.facts.length ? `### ${t.facts}\n` + sec.facts.map((f) => `- ${f}`).join('\n') : '',
          sec.gaps.length ? `\n### ${t.gaps}\n` + sec.gaps.map((g) => `- ${g}`).join('\n') : '',
        ]
          .filter(Boolean)
          .join('\n'),
        ['baza-znanja']
      );
    }
  }

  // ── Hub (MOC) ──
  const hub = `${fm({
    tags: ['ai-validator', 'projekt', 'moc'],
    project,
    score: report.score,
    buy: report.intent.buy,
    maybe: report.intent.maybe,
    reject: report.intent.reject,
    generated: date,
    source: 'AI Validator',
  })}

# ${project}

> ${t.score}: **${report.score}/100** · ${t.buy} ${report.intent.buy}% · ${t.maybe} ${report.intent.maybe}% · ${t.reject} ${report.intent.reject}%

${report.summary || ''}

## ${t.notes}
${childLinks.join('\n')}

---
*${t.generatedBy} · ${date}*
`;

  notes.unshift({ path: `${dir}/${safeName(project)}.md`, markdown: hub });

  return notes;
}
